### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by miskatonicstudio** [miskatonicstudio/goat#1]
Set it in README and in Godot project settings.

**Comment by WesBlanko** [comment]
I´ve just read this, got inspired and made some quick n dirty design.

![GOAT](https://user-images.githubusercontent.com/30173796/75540322-19ffcc80-5a1c-11ea-964d-f025188a74ff.png)

[GOAT.zip](https://github.com/miskatonicstudio/goat/files/4266503/GOAT.zip)

**Comment by miskatonicstudio** [comment]
Wow! I didn't expect anyone to design a logo so fast, thank you very much! Your idea is interesting, and completely different than what I had in mind :D I was thinking about something similar to Godot robot's head, but with a goatee and horns ;) Assuming, of course, that Godot maintainers would be ok with that.

But I like your idea too and I'm open for discussion ;) Do you think you could design something a bit simpler, that would look good as a miniature? And would it be possible to release your work under Creative Commons/public domain?

**Comment by WesBlanko** [comment]
I checked my mails every half an hour after posting it and... missed your reaction hours later xD.

Glad you like it too. Of course I experiment with it tomorrow and yeah I don’t care which license. CC0 is probably the best Option or CCby[GOAT] if ya like.

I am all legion for this. ;)

**Comment by WesBlanko** [comment]
![GOATZ](https://user-images.githubusercontent.com/30173796/75605748-b93cc680-5ae5-11ea-8748-e6c1706637d0.png)
[GOATZ.zip](https://github.com/miskatonicstudio/goat/files/4270164/GOATZ.zip)

License: CC0

**Comment by miskatonicstudio** [comment]
Thank you for your amazing work @WesBlanko ! I have decided, however, to use another, more simple logo. It is already added to README and docs.

I'm really glad that you've found the time to work on your version and I'm sorry that it was not used, but I hope it will not discourage you from engaging in the project's development ;)
