### ISSUE TITLE
Attach random sounds to InteractiveItem

### ISSUE THREAD

**Issue by miskatonicstudio** [miskatonicstudio/goat#214]
This could be made by either extending an InteractiveItem scene to include a list of sounds or by using a custom audio player with many samples (similar solution was made by Tim Krief and is available in Godot's assets).

**Comment by timkrief** [comment]
I'm going to release shortly my add-on called "Random Audio Stream Player" that could solve this.

**Comment by timkrief** [comment]
It's not yet in the asset store, but a first version is available here : https://gitlab.com/timkrief/godot-random-audio-stream-player
