### ISSUE TITLE
Mouse cursor disappears when the demo project restarts (full screen).

### ISSUE THREAD

**Issue by Sslaxx** [miskatonicstudio/goat#219]
Running the GOAT Demo project with Godot 3.2 in full screen, once the demo has ended and restarts at the main menu once more, the mouse cursor is not visible.

Valid as of https://github.com/miskatonicstudio/goat/commit/0e12c7fecaf53a0798ee5faf24526c6e3378f283 (also of at least several commits before).

**Comment by miskatonicstudio** [comment]
Thanks for reporting this, I'll check it on my machine. Can you provide more details, e.g. which OS did you use for this test?

**Comment by miskatonicstudio** [comment]
I just checked it on Ubuntu 18.04. After the game ends (click on portal => screen slowly goes white) and the credits screen is shown (I didn't skip it), the game goes back to the main menu and the mouse cursor is displayed correctly. Is that the same scenario that you've tested? Could you provide screenshots of this issue?

**Comment by Sslaxx** [comment]
This is happening with Windows 10. Nvidia drivers.

**Comment by miskatonicstudio** [comment]
I was able to replicate it on Windows 10 (without Nvidia drivers). I'll start working on a fix.

**Comment by miskatonicstudio** [comment]
I've tried setting the mouse mode at the end of the credits scene, removing the custom cursor, and using the latest version of Godot (3.2.1 stable). Nothing worked. When I switch to another application and back using Alt+Tab, the cursor is shown correctly.

I will copy this to Godot issues and wait for their solution.

**Comment by miskatonicstudio** [comment]
It seems that this one was fixed in Godot 3.2.2 (https://github.com/godotengine/godot/pull/39750). I've confirmed that is works on Windows, so I'm closing this issue. If you find any problems with it again @Sslaxx , please feel free to reopen.
