### ISSUE TITLE
InteractionIcon: white quad instead of textures 

### ISSUE THREAD

**Issue by Kame7C0** [miskatonicstudio/goat#238]
there are some changes to sprite3D in godot 3.2.3 - check godot issue:
https://github.com/godotengine/godot/issues/33234

**Comment by miskatonicstudio** [comment]
Thanks @CezaryKopias for reporting this! I'll check the issue and possibly fix it soon ;)

**Comment by CezaryKopias** [comment]
as a poors man fix i did:
```
func _on_InteractionIcon_visibility_changed():
    material_override.albedo_texture = texture

```

**Comment by miskatonicstudio** [comment]
@Kame7C0 thanks for the hint ;) I've added a separate material for each interactive icon and set the albedo texture there. It seems to work with both Godot 3.2.3 and 3.2.stable. If it still doesn't work on your machine, please feel free to reopen this issue.

Also, did you encounter any other problems with migration to 3.2.3? If not, I could update the label and README icon to display 3.2.3 version ;)
