### ISSUE TITLE
GRAVITY_ENABLED = true in goat script appers as false in player script

### ISSUE THREAD

**Issue by IvailoBurov** [miskatonicstudio/goat#246]
It's strange, however this happens when testing the project with Godot 3.2.3.
So, I exported this variable to the Player script.
I don't know why the project is limited only to an FPS camera, since Third Person camera can also be successfully used with any option to switch cameras.
I tried this with Spring Node and it works successfully. Interactive objects are selectable too. Also jump code works and there is no limit to flat surfaces only with capsule collision shape.

**Comment by miskatonicstudio** [comment]
Thanks for reaching out!

Regarding the camera: there are several options that could be useful for adventure games, including first person camera, third person camera following a character or even a static camera per room (like in J.U.L.I.A). The reason why GOAT has only one of them is that the project is relatively new and developed mostly by a single person :) Hopefully, these things will be implemented at some point, but other issues were more urgent by far. There is, however, a task for extracting the camera logic out of the Player scene an creating reusable cameras: https://github.com/miskatonicstudio/goat/issues/70

Regarding the `GRAVITY_ENABLED` flag: version 3.2.3 is not currently supported, I'm waiting for the huge 4.0 update to make sure that GOAT works with it. That being said, if fixing this issue in 3.2.3 will not be a big problem, I'll take care of it. Could you confirm that 3.2.stable.official works on your machine?

**Comment by miskatonicstudio** [comment]
Hi again!

GOAT now uses Godot 3.4.2, and there's been an update to the gravity logic recently. I believe this problem is now fixed :)

(If not, feel free to reopen this issue!)
