### ISSUE TITLE
Cursor disappearing...

### ISSUE THREAD

**Issue by paulicka** [miskatonicstudio/goat#254]
...when RMB in inventory, either with or without an object to roate in inventory yet.
(Rotation works fine when there is an object, cursor goes away for that, but then...never comes back!)

And haven't found a way to get it back without restarting.

Love GOAT!  Such a wonderful tool, and I'm hoping to use it in the current Godot Wild Jam.

I am running on a mac, with Godot 3.2.1, and I get a warning about the randomAudio addon not working first time (just to setup the issue).

**Comment by miskatonicstudio** [comment]
Hi! Thank you for reaching out ;) Unfortunately, testing on Mac is a bit problematic, as I don't own one :smile: I know there were some problems with misbehaving cursor when I tried to e.g. set a custom icon, but I think those were solved in Godot 3.2 ...

One thing I could suggest is using another mouse mode. GOAT inventory sets it to `MOUSE_MODE_VISIBLE` when you're done rotating an item. Could you check if setting it to e.g. `MOUSE_MODE_CONFINED` solves the problem?

**Comment by paulicka** [comment]
Actually, updating from 3.2.1 to 3.2.3 solved the problem!  Yay!
