### ISSUE TITLE
Implement dialogs

### ISSUE THREAD

**Issue by miskatonicstudio** [miskatonicstudio/goat#33]
Allow player to pick a dialog option and react accordingly.

**Comment by WesBlanko** [comment]
I would add the option to use Items/actions during dialoges

**Comment by miskatonicstudio** [comment]
That is a good idea! I think the model used in Shadowrun computer games could work: when an item is in the inventory, we see an additional dialogue option, e.g.:

`"[USB drive] I've found this USB drive, could you extract any information out of it?"`

Is that what you had in mind or did you mean something else?

**Comment by WesBlanko** [comment]
> That is a good idea! I think the model used in Shadowrun computer games could work: when an item is in the inventory, we see an additional dialogue option, e.g.:
> 
> `"[USB drive] I've found this USB drive, could you extract any information out of it?"`
> 

Seems like I missed it in the 15 mins I played Shadowrun returns so far. I love this mechanic. Very elegant and nerdy.

> Is that what you had in mind or did you mean something else?

I recently started “Whispers of a machine” in which you could show/talk about Items, got some Biofeedback actions (similar to DeusEx:HR) and the classic Dialogue Options. But they used just the Inventory meanwhile the Dialogues.

Personally I even think of per Situation based different Dialogue UI. Maybe a 3 Tier layered approach depending how important the Conversation is. You clearly don’t need anything in every dialogue. 

Maybe it’s the best to make it somewhat modular for the designer/player. Here would be even room for a casual and hardcore mode.

Interesting

**Comment by timkrief** [comment]
There are a lot of dialogue systems being made for Godot and while it offers variety, it also make them less supported than if we were all working on the same project. We should check if a dialogue solution that fits GOAT's need already exists and if it does use it / contribute to it. What do you think about that ?

**Comment by miskatonicstudio** [comment]
That sounds like a good idea! I know there is already an adventure game project: Escoria, currently refactored by @StraToN. There are certainly many elements that GOAT could use, and maybe contribute to. Do you have any other examples in mind @timkrief ?

**Comment by miskatonicstudio** [comment]
Implemented in #326 .
